#!/bin/bash

# Applications
alias st="/Applications/Sublime\ Text\ 2.app/Contents/SharedSupport/bin/subl"

function vlc () {
  open -a vlc $1 --args -Z --crop=16:10
}

# Bash Management
alias ea='vim -N ~/bin/dotfiles/bash/aliases'
alias ec='vim -N ~/bin/dotfiles/bash/config'
alias ee='vim -N ~/bin/dotfiles/bash/env'
alias sb='source ~/.bashrc'

# Directory Management
alias ..='cd ../'
alias ...=../'cd ../'
alias ~='cd ~'
alias cdc='cd ~/code/'
alias cdd='cd -'
alias cdw='cd ~/Workspace/'
alias ll='ls -AGhl'
alias ls='ls -AGh'
alias md='mkdir -p'
alias rd='rm -rf'

# Show/hide hidden files in Finder
alias shf="defaults write com.apple.Finder AppleShowAllFiles -bool true && killall Finder"
alias hhf="defaults write com.apple.Finder AppleShowAllFiles -bool false && killall Finder"

function take () {
  mkdir -p $1
  cd $1
}

# Git
alias gbc='git checkout -b'
alias gbd='git branch -D'
alias gci='git commit -vs'
alias gcl='git clone'
alias gcm='git checkout master'
alias gco='git checkout'
alias glg='git log --pretty=format:"%an: %s (%h)"'
alias gpl='git pull'
alias gpm='git push origin master'
alias gpo='git push origin'
alias gps='git push'
alias gst='git status'

function ggrep () {
  git grep $1 $(git log -g --pretty=format:%h -S$1)
}

# Misc
alias ev='vim ~/bin/dotfiles/vimrc'
alias nd='node-dev'
alias tm='top -o vsize'
alias tu='top -o cpu'

# Hide/show all desktop icons (useful when screencasting)
alias hdi="defaults write com.apple.finder CreateDesktop -bool false && killall Finder"
alias sdi="defaults write com.apple.finder CreateDesktop -bool true && killall Finder"

# Music
function play () {
  open -a "vlc" ~/Music/playlists/$1.m3u --args --no-random
}
