#!/bin/bash

# Enable aliases to be sudo'ed
alias sudo='sudo '

# Applications
alias st="/Applications/Sublime\ Text\ 2.app/Contents/SharedSupport/bin/subl"

function vlc () {
  open -a vlc $1 --args -Z --crop=16:10
}

# Bash Management
alias ea='vim -N ~/bin/dotfiles/bash/aliases'
alias ec='vim -N ~/bin/dotfiles/bash/config'
alias ee='vim -N ~/bin/dotfiles/bash/env'
alias sb='source ~/.bashrc'

# Directory Management
alias ..='cd ../'
alias ...=../'cd ../'
alias ~='cd ~'
alias cdc='cd ~/code/'
alias cdd='cd -'
alias cdw='cd ~/Workspace/'
alias ll='ls -AFGhl'
alias ls='ls -AFGh'
alias md='mkdir -p'
alias rm='rm -i'

# Show/hide hidden files in Finder
alias shf="defaults write com.apple.Finder AppleShowAllFiles -bool true && killall Finder"
alias hhf="defaults write com.apple.Finder AppleShowAllFiles -bool false && killall Finder"

function take () {
  md $1
  cd $1
}

# Git
alias git='hub'
alias gbc='git checkout -b'
alias gbd='git branch -D'
alias gci='git commit -vs'
alias gcl='git clone'
alias gcm='git checkout master'
alias gco='git checkout'
alias gff='git flow feature'
alias glg='git log --pretty=format:"%an: %s (%h)"'
alias gpl='git pull'
alias gpm='git push origin master'
alias gpo='git push origin'
alias gps='git push'
alias gst='git status'

function ggrep () {
  git grep $1 $(git log -g --pretty=format:%h -S$1)
}

# Misc
alias ev='vim ~/bin/dotfiles/vimrc'
alias nd='node-dev'
alias nw='/Applications/node-webkit.app/Contents/MacOS/node-webkit'
alias tm='top -o vsize'
alias tu='top -o cpu'

# NPM
alias ni='npm install --save'
alias nd='npm uninstall --save'

# Hide/show all desktop icons (useful when screencasting)
alias hdf="defaults write com.apple.finder CreateDesktop -bool false && killall Finder"
alias sdf="defaults write com.apple.finder CreateDesktop -bool true && killall Finder"

# Music
function play () {
  open -a "vlc" ~/Music/playlists/$1.m3u --args --no-random
}

# Empty the Trash on all mounted volumes and the main HDD
# Also, clear Apple’s System Logs to improve shell startup speed
alias emptytrash="sudo rm -rfv /Volumes/*/.Trashes; sudo rm -rfv ~/.Trash; sudo rm -rfv /private/var/log/asl/*.asl"
